### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by locness3** [Pufflegamerz/PrismOS#4]
How do you install it on a Mac ?

**Comment by locness3** [comment]
Without replacing macOS

**Comment by Pufflegamerz** [comment]
I think you may be able to run it in virtualbox.

**Comment by locness3** [comment]
Which iso ?

**Comment by Pufflegamerz** [comment]
This one: https://github.com/Pufflegamerz/PrismOS/blob/master/PrismOSv0.2.iso

**Comment by locness3** [comment]
Ok. Maybe I will try if I can.
